config/routes.rb
Rails.application.routes.draw do
  resources :awards
  resources :academies
  resources :actors
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'actors#index'
  # get 'academies#index'
  # get 'awards#index'
end

app/models/academy.rb
class Academy < ApplicationRecord
      has_many :actors 
end

app/models/actor.rb
class Actor < ApplicationRecord
  has_many :awards
  belongs_to :academy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/award.rb
class Award < ApplicationRecord
      has_many :actors
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/academies_controller.rb
class AcademiesController < ApplicationController
  before_action :set_academy, only: [:show, :edit, :update, :destroy]

  # GET /academies
  # GET /academies.json
  def index
    @academies = Academy.all
  end

  # GET /academies/1
  # GET /academies/1.json
  def show
  end

  # GET /academies/new
  def new
    @academy = Academy.new
  end

  # GET /academies/1/edit
  def edit
  end

  # POST /academies
  # POST /academies.json
  def create
    @academy = Academy.new(academy_params)

    respond_to do |format|
      if @academy.save
        format.html { redirect_to @academy, notice: 'Academy was successfully created.' }
        format.json { render :show, status: :created, location: @academy }
      else
        format.html { render :new }
        format.json { render json: @academy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /academies/1
  # PATCH/PUT /academies/1.json
  def update
    respond_to do |format|
      if @academy.update(academy_params)
        format.html { redirect_to @academy, notice: 'Academy was successfully updated.' }
        format.json { render :show, status: :ok, location: @academy }
      else
        format.html { render :edit }
        format.json { render json: @academy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /academies/1
  # DELETE /academies/1.json
  def destroy
    @academy.destroy
    respond_to do |format|
      format.html { redirect_to academies_url, notice: 'Academy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_academy
      @academy = Academy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def academy_params
      params.require(:academy).permit(:name, :location)
    end
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  before_action :set_actor, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /actors
  # GET /actors.json
  def index
    @actors = Actor.all
  end

  # GET /actors/1
  # GET /actors/1.json
  def show
    @awards = Award.where(:actor_id == @actor.id)
  end

  # GET /actors/new
  def new
    @actor = Actor.new
  end

  # GET /actors/1/edit
  def edit
  end


  # POST /actors
  # POST /actors.json
  def create
    @actor = Actor.new(actor_params)

    respond_to do |format|
      if @actor.save
        format.html { redirect_to @actor, notice: 'Actor was successfully created.' }
        format.json { render :show, status: :created, location: @actor }
      else
        format.html { render :new }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /actors/1
  # PATCH/PUT /actors/1.json
  def update
    respond_to do |format|
      if @actor.update(actor_params)
        format.html { redirect_to @actor, notice: 'Actor was successfully updated.' }
        format.json { render :show, status: :ok, location: @actor }
      else
        format.html { render :edit }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /actors/1
  # DELETE /actors/1.json
  def destroy
    @actor.destroy
    respond_to do |format|
      format.html { redirect_to actors_url, notice: 'Actor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_actor
      @actor = Actor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def actor_params
      params.require(:actor).permit(:first_name, :last_name, :age, :description, :academy_id, :award_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/awards_controller.rb
class AwardsController < ApplicationController
  before_action :set_award, only: [:show, :edit, :update, :destroy]

  # GET /awards
  # GET /awards.json
  def index
    @awards = Award.all
  end

  # GET /awards/1
  # GET /awards/1.json
  def show
  end

  # GET /awards/new
  def new
    @award = Award.new
  end

  # GET /awards/1/edit
  def edit
  end

  # POST /awards
  # POST /awards.json
  def create
    @award = Award.new(award_params)

    respond_to do |format|
      if @award.save
        format.html { redirect_to @award, notice: 'Award was successfully created.' }
        format.json { render :show, status: :created, location: @award }
      else
        format.html { render :new }
        format.json { render json: @award.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /awards/1
  # PATCH/PUT /awards/1.json
  def update
    respond_to do |format|
      if @award.update(award_params)
        format.html { redirect_to @award, notice: 'Award was successfully updated.' }
        format.json { render :show, status: :ok, location: @award }
      else
        format.html { render :edit }
        format.json { render json: @award.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /awards/1
  # DELETE /awards/1.json
  def destroy
    @award.destroy
    respond_to do |format|
      format.html { redirect_to awards_url, notice: 'Award was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_award
      @award = Award.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def award_params
      params.require(:award).permit(:name, :category, :year, :actor_id )
    end
end

app/helpers/academies_helper.rb
module AcademiesHelper
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/awards_helper.rb
module AwardsHelper
end

app/views/academies/_form.html.erb
<%= form_with(model: academy, local: true) do |form| %>
  <% if academy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(academy.errors.count, "error") %> prohibited this academy from being saved:</h2>

      <ul>
      <% academy.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <br>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <br>
    <%= form.text_field :location %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/academies/edit.html.erb
<h1>Editing Academy</h1>

<%= render 'form', academy: @academy %>

<%= link_to 'Show', @academy %> |
<%= link_to 'Back', academies_path %>

app/views/academies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Academies</h1>

<table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Location</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @academies.each do |academy| %>
          <tr>
            <td><%= academy.name %></td>
            <td><%= academy.location %></td>
            <td><%= link_to 'Show', academy %></td>
            <td><%= link_to 'Edit', edit_academy_path(academy) %></td>
            <td><%= link_to 'Destroy', academy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
</table>

<br>

<%= link_to 'New Academy', new_academy_path,:class => 'btn btn-danger' %>
<%= link_to 'Actors', actors_path, :class => 'btn btn-primary' %>
<%= link_to 'Awards', awards_path, :class => 'btn btn-warning'  %>

app/views/academies/new.html.erb
<h1>New Academy</h1>

<%= render 'form', academy: @academy %>

<%= link_to 'Back', academies_path %>

app/views/academies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @academy.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @academy.location %>
</p>

<%= link_to 'Edit', edit_academy_path(@academy) %> |
<%= link_to 'Back', academies_path %>

app/views/actors/_form.html.erb
<%= form_with(model: actor, local: true) do |form| %>
  <% if actor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(actor.errors.count, "error") %> prohibited this actor from being saved:</h2>

      <ul>
      <% actor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <br>
    <%= form.text_field :first_name %>
  </div>
  <div class="field">
    <%= form.label :last_name %>
    <br>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <br>
    <%= form.number_field :age %>
  </div>
<br>
  <div class="field">
    <%= form.label :description %>
    <br>
    <%= form.text_area :description %>
  </div>
  <br>
  <div class="field">
    <%= form.label :academy_id %>
    <br>
    <%= form.text_area :academy_id %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/actors/edit.html.erb
<h1>Editing Actor</h1>

<%= render 'form', actor: @actor %>

<%= link_to 'Show', @actor %> |
<%= link_to 'Back', actors_path %>

app/views/actors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Actors</h1>

<table class="table">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Age</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @actors.each do |actor| %>
      <tr>
        <td><%= actor.first_name %></td>
        <td><%= actor.last_name %></td>
        <td><%= actor.age %></td>
        <td><%= actor.description %></td>
        <td><%= link_to 'Show', actor %></td>
        <td><%= link_to 'Edit', edit_actor_path(actor) %></td>
        <td><%= link_to 'Destroy',actor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New Actor', new_actor_path, :class => 'btn btn-primary' %>
<%= link_to 'Award', awards_path, :class => 'btn btn-warning'%>
<%= link_to 'Academy', academies_path, :class => 'btn btn-danger'%>
<br>
<br>
<img src="robin.jpg" alt="tulli" width="200" height="250">
<img src="anne.jpg" alt="tulli" width="200" height="250">
<img src="jessica-chastain.jpg"  width="250" height="250">
<img src="viola-davis-1.jpg"  width="250" height="250">

app/views/actors/new.html.erb
<h1>New Actor</h1>
<%= render 'form', actor: @actor %>


<%= link_to 'Back', actors_path %>

app/views/actors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @actor.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @actor.last_name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @actor.age %>
</p>

<p>
  <strong>Description:</strong>
  <%= @actor.description %>
</p>

<p>
  <strong>Academy Name:</strong>
  <%= @actor.academy.name %>
</p>
<p>
  <strong>Academy Location:</strong>
  <%= @actor.academy.location %>
</p>


<p> <strong>Awards:</strong></p>
    <% @awards.each do |award| %>
     <% if @actor.id == award.actor_id%>
      <tr>
        <td><%= award.name %></td>
        <td><%= award.category %></td>
        <td><%= award.year %></td>
        <br>
      </tr>
    <% end %>
   <% end %>

<%= link_to 'Edit', edit_actor_path(@actor) %> |
<%= link_to 'Back', actors_path %>

app/views/awards/_form.html.erb
<%= form_with(model: award, local: true) do |form| %>
  <% if award.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(award.errors.count, "error") %> prohibited this award from being saved:</h2>

      <ul>
      <% award.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <br>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <br>
    <%= form.text_field :category %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <br>
    <%= form.number_field :year %>
  </div>

    <div class="field">
      <%= form.label :actor_id%>
      <br>
      <%= form.number_field :actor_id%>
    </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/awards/edit.html.erb
<h1>Editing Award</h1>

<%= render 'form', award: @award %>

<%= link_to 'Show', @award %> |
<%= link_to 'Back', awards_path %>

app/views/awards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Awards</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Category</th>
      <th>Year</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @awards.each do |award| %>
      <tr>
        <td><%= award.name %></td>
        <td><%= award.category %></td>
        <td><%= award.year %></td>
        <td><%= link_to 'Show', award %></td>
        <td><%= link_to 'Edit', edit_award_path(award) %></td>
        <td><%= link_to 'Destroy', award, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New Award', new_award_path, :class => 'btn btn-warning'%>
<%= link_to 'Actor', actors_path, :class => 'btn btn-primary' %>
<%= link_to 'Academy',academies_path, :class => 'btn btn-danger'%>

<br>
<br>
<img src="oscars.jpg"  width="200" height="250">
<img src="golden.jpg"  width="270" height="250">
<img src="BET.jpg"  width="270" height="250"> 

app/views/awards/new.html.erb
<h1>New Award</h1>

<%= render 'form', award: @award %>

<%= link_to 'Back', awards_path %>

app/views/awards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @award.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @award.category %>
</p>

<p>
  <strong>Year:</strong>
  <%= @award.year %>
</p>

<%= link_to 'Edit', edit_award_path(@award) %> |
<%= link_to 'Back', awards_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Actors Wikipedia</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag  'https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <button type="button"
    onclick="document.getElementById('demo').innerHTML = Date()">
    Date and Time</button>

    <p id="demo"></p>
      <% if user_signed_in? %>
      <div class="log">
         Logged in as <strong><%= current_user.email %></strong>.
      </div>
        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
        <% else %>
        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link' %> |
        <%= link_to "Login", new_user_session_path, :class => 'navbar-link' %>
        <% end %>
      <%= yield %>
  </body>
</html>